project:
  type: website
  resources:
    - ".well-known/brave-rewards-verification.txt"
  output-dir: docs

website:
  title: "jkunze"
  navbar:
    left:
      - href: index.qmd
        text: Home

#      - href: posts/welcome/index.qmd
#        text: blog

format:
  html:
    css: styles.css
    toc: false

#    toc: true
#    theme: zephyr

